version: '3'

volumes:
  database2: {}

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'budget'
      MYSQL_USER: 'budget'
      MYSQL_PASSWORD: 'test'
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: ./
    environment:
      - BUDGET_SETUP
    volumes:
      - .:/var/www
    ports:
      - 8080:80
    command: ./docker_boot.sh
